export interface WMOWeatherMeta {
  code: number;
  label: string;
  description: string;
  category: 'clear' | 'cloudy' | 'fog' | 'drizzle' | 'rain' | 'snow' | 'thunderstorm';
  iconName: string;
  gradientClass: string;
  badgeBg: string;
  badgeText: string;
}

export const WMO_CODES: Record<number, WMOWeatherMeta> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Completely clear skies with strong sunshine or starry night.',
    category: 'clear',
    iconName: 'Sun',
    gradientClass: 'from-amber-500/20 via-orange-500/10 to-transparent',
    badgeBg: 'bg-amber-500/20',
    badgeText: 'text-amber-300',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly sunny with minimal cloud cover.',
    category: 'clear',
    iconName: 'SunMedium',
    gradientClass: 'from-amber-500/20 via-amber-600/10 to-transparent',
    badgeBg: 'bg-amber-500/20',
    badgeText: 'text-amber-300',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'Scattered clouds with periods of sunshine.',
    category: 'cloudy',
    iconName: 'CloudSun',
    gradientClass: 'from-sky-500/20 via-slate-600/10 to-transparent',
    badgeBg: 'bg-sky-500/20',
    badgeText: 'text-sky-300',
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'Fully covered gray skies.',
    category: 'cloudy',
    iconName: 'Cloud',
    gradientClass: 'from-slate-600/30 via-slate-700/20 to-transparent',
    badgeBg: 'bg-slate-600/30',
    badgeText: 'text-slate-300',
  },
  45: {
    code: 45,
    label: 'Foggy',
    description: 'Dense fog reducing visibility.',
    category: 'fog',
    iconName: 'CloudFog',
    gradientClass: 'from-teal-600/20 via-slate-700/20 to-transparent',
    badgeBg: 'bg-teal-500/20',
    badgeText: 'text-teal-300',
  },
  48: {
    code: 48,
    label: 'Depositing Rime Fog',
    description: 'Freezing fog depositing ice crystals.',
    category: 'fog',
    iconName: 'CloudFog',
    gradientClass: 'from-teal-700/20 via-slate-800/20 to-transparent',
    badgeBg: 'bg-teal-600/20',
    badgeText: 'text-teal-200',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'Fine intermittent drizzle.',
    category: 'drizzle',
    iconName: 'CloudDrizzle',
    gradientClass: 'from-blue-500/20 via-sky-600/10 to-transparent',
    badgeBg: 'bg-blue-500/20',
    badgeText: 'text-blue-300',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Steady light drizzle precipitation.',
    category: 'drizzle',
    iconName: 'CloudDrizzle',
    gradientClass: 'from-blue-600/20 via-indigo-600/10 to-transparent',
    badgeBg: 'bg-blue-600/20',
    badgeText: 'text-blue-300',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Heavy drizzle reducing visibility.',
    category: 'drizzle',
    iconName: 'CloudDrizzle',
    gradientClass: 'from-blue-700/20 via-indigo-700/10 to-transparent',
    badgeBg: 'bg-blue-700/20',
    badgeText: 'text-blue-200',
  },
  56: {
    code: 56,
    label: 'Freezing Drizzle',
    description: 'Light freezing drizzle creating slippery surfaces.',
    category: 'drizzle',
    iconName: 'CloudHail',
    gradientClass: 'from-cyan-600/20 via-blue-700/20 to-transparent',
    badgeBg: 'bg-cyan-600/20',
    badgeText: 'text-cyan-200',
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    description: 'Heavy freezing drizzle with ice risk.',
    category: 'drizzle',
    iconName: 'CloudHail',
    gradientClass: 'from-cyan-700/20 via-blue-800/20 to-transparent',
    badgeBg: 'bg-cyan-700/20',
    badgeText: 'text-cyan-200',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Light rain showers.',
    category: 'rain',
    iconName: 'CloudRain',
    gradientClass: 'from-blue-600/25 via-indigo-600/15 to-transparent',
    badgeBg: 'bg-blue-600/20',
    badgeText: 'text-blue-300',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Steady rainfall across the area.',
    category: 'rain',
    iconName: 'CloudRain',
    gradientClass: 'from-blue-700/30 via-indigo-700/20 to-transparent',
    badgeBg: 'bg-blue-700/25',
    badgeText: 'text-blue-200',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Heavy torrential downpour.',
    category: 'rain',
    iconName: 'CloudRainWind',
    gradientClass: 'from-blue-800/40 via-indigo-900/30 to-transparent',
    badgeBg: 'bg-blue-800/30',
    badgeText: 'text-blue-100',
  },
  66: {
    code: 66,
    label: 'Freezing Rain',
    description: 'Freezing rainfall creating ice sheets.',
    category: 'rain',
    iconName: 'CloudHail',
    gradientClass: 'from-cyan-600/30 via-sky-800/20 to-transparent',
    badgeBg: 'bg-cyan-600/30',
    badgeText: 'text-cyan-200',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Heavy freezing rain causing hazardous black ice.',
    category: 'rain',
    iconName: 'CloudHail',
    gradientClass: 'from-cyan-700/40 via-sky-900/30 to-transparent',
    badgeBg: 'bg-cyan-700/35',
    badgeText: 'text-cyan-100',
  },
  71: {
    code: 71,
    label: 'Slight Snow',
    description: 'Light snowfall with delicate flakes.',
    category: 'snow',
    iconName: 'Snowflake',
    gradientClass: 'from-sky-400/20 via-indigo-500/10 to-transparent',
    badgeBg: 'bg-sky-400/20',
    badgeText: 'text-sky-200',
  },
  73: {
    code: 73,
    label: 'Moderate Snow',
    description: 'Steady snowfall building accumulation.',
    category: 'snow',
    iconName: 'Snowflake',
    gradientClass: 'from-sky-500/25 via-indigo-600/15 to-transparent',
    badgeBg: 'bg-sky-500/25',
    badgeText: 'text-sky-100',
  },
  75: {
    code: 75,
    label: 'Heavy Snow',
    description: 'Heavy snowfall with severe accumulation.',
    category: 'snow',
    iconName: 'Snowflake',
    gradientClass: 'from-sky-600/35 via-indigo-700/25 to-transparent',
    badgeBg: 'bg-sky-600/35',
    badgeText: 'text-white',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Very small white opaque ice grains.',
    category: 'snow',
    iconName: 'Snowflake',
    gradientClass: 'from-slate-500/20 via-sky-600/10 to-transparent',
    badgeBg: 'bg-slate-500/20',
    badgeText: 'text-sky-200',
  },
  80: {
    code: 80,
    label: 'Slight Rain Showers',
    description: 'Passing light rain showers.',
    category: 'rain',
    iconName: 'CloudRain',
    gradientClass: 'from-blue-500/20 via-sky-600/10 to-transparent',
    badgeBg: 'bg-blue-500/20',
    badgeText: 'text-blue-300',
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    description: 'Intermittent moderate showers.',
    category: 'rain',
    iconName: 'CloudRain',
    gradientClass: 'from-blue-600/30 via-sky-700/20 to-transparent',
    badgeBg: 'bg-blue-600/25',
    badgeText: 'text-blue-200',
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    description: 'Sudden intense torrential downpours.',
    category: 'rain',
    iconName: 'CloudRainWind',
    gradientClass: 'from-blue-800/40 via-purple-900/30 to-transparent',
    badgeBg: 'bg-blue-800/35',
    badgeText: 'text-blue-100',
  },
  85: {
    code: 85,
    label: 'Slight Snow Showers',
    description: 'Passing snow flurries.',
    category: 'snow',
    iconName: 'Snowflake',
    gradientClass: 'from-sky-400/20 via-slate-600/10 to-transparent',
    badgeBg: 'bg-sky-400/20',
    badgeText: 'text-sky-200',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Heavy passing snow flurries.',
    category: 'snow',
    iconName: 'Snowflake',
    gradientClass: 'from-sky-600/30 via-indigo-800/20 to-transparent',
    badgeBg: 'bg-sky-600/30',
    badgeText: 'text-white',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Thunderstorm with lightning and gusty winds.',
    category: 'thunderstorm',
    iconName: 'CloudLightning',
    gradientClass: 'from-purple-600/35 via-violet-900/25 to-transparent',
    badgeBg: 'bg-purple-600/30',
    badgeText: 'text-purple-200',
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Hail',
    description: 'Severe thunderstorm accompanied by light hail.',
    category: 'thunderstorm',
    iconName: 'CloudLightning',
    gradientClass: 'from-purple-700/40 via-fuchsia-900/30 to-transparent',
    badgeBg: 'bg-purple-700/35',
    badgeText: 'text-purple-100',
  },
  99: {
    code: 99,
    label: 'Heavy Thunderstorm with Hail',
    description: 'Dangerous thunderstorm with heavy damaging hail.',
    category: 'thunderstorm',
    iconName: 'CloudLightning',
    gradientClass: 'from-rose-800/40 via-purple-950/40 to-transparent',
    badgeBg: 'bg-rose-800/40',
    badgeText: 'text-rose-200',
  },
};

export function getWMOMeta(code: number): WMOWeatherMeta {
  return (
    WMO_CODES[code] || {
      code,
      label: 'Variable Weather',
      description: 'Changing meteorological conditions.',
      category: 'cloudy',
      iconName: 'Cloud',
      gradientClass: 'from-slate-600/20 to-transparent',
      badgeBg: 'bg-slate-600/20',
      badgeText: 'text-slate-300',
    }
  );
}

export function convertTemperature(celsius: number, unit: 'celsius' | 'fahrenheit'): number {
  if (unit === 'fahrenheit') {
    return Math.round((celsius * 9) / 5 + 32);
  }
  return Math.round(celsius);
}

export function formatTempString(celsius: number, unit: 'celsius' | 'fahrenheit'): string {
  const val = convertTemperature(celsius, unit);
  return `${val}°${unit === 'fahrenheit' ? 'F' : 'C'}`;
}
